### ISSUE TITLE
Should we put the registration function for P2P connections back in?

### ISSUE THREAD

**Issue by jhned** [Clark-Nikdel-Powell/client-core-legacy#1]
Hey Glenn, it looks like you moved the P2P connection registration function out of here way back in last year. I think that's the sort of thing that we could use in this plugin though-- anything where we're configuring settings, or registering different things. What do you think?

**Comment by gwelser** [comment]
I'm not entirely sure why I moved it out. It's not a decision I would have made on my own but I can't recall the discussion around it.

My question would be, how often do we use P2P connections? If it's not often, then I would argue we leave it out. However, if the majority of the themes we create require those connections, then let's put it back in.

**Comment by jhned** [comment]
We don't use Posts 2 Posts Connections often. But there is something to be said for the convenience of having all the site registration functionality in one place.

If we did leave it out, I would want to put those registrations in a plugin anyway, so that the data is kept separate from the theme.

**Comment by gwelser** [comment]
I can see the convenience of having all the registrations in one place, yes. Doesn't ACF have a Relationship field and isn't it essentially the same thing as P2P?

**Comment by jhned** [comment]
Good thought! It's very similar. I can see two advantages for P2P:

1. The registration is defined in a file vs. defined in the DB, so it's harder to lose it. 
2. I don't think the ACF Relationship field is reciprocal.

**Comment by gwelser** [comment]
You mean in ACF, relationship isn't two-way? Yeah I can see that being a good case for P2P then.

**Comment by jhned** [comment]
Correct, ACF doesn't do two-way.
